server:
  port: 8080

---
spring:
  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:studymoim-gcs.json
logging:
  level:
    web: info
    sql: info
springdoc:
  use-fqn: true
oauth:
  kakao:
    redirect-context: localhost
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 
    username: 
    password: 
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:studymoim-gcs.json
logging:
  level:
    web: trace
    sql: trace
springdoc:
  use-fqn: true
oauth:
  kakao:
    redirect-context: i8a110.p.ssafy.io
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 
    username: 
    password: 
  jpa:
    database: mysql
  springdoc:
    use-fqn: true
logging:
  level:
    web: error
    sql: error
---
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 
            redirect-uri: 
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
---
# unit is ms. 15 * 24 * 60 * 60 * 1000 = 1day, 86400000ms
jwt:
  secret: 
  expiration: 86400000


youtubeapi:
  secret:
